
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fpufutmr/public_html/
    - npm install
    - npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp public/sitemap.xml $DEPLOYPATH
---
