---
deployment:
  tasks:
    - current_branch=$(git branch --show-current) # set current branch to variable
    - if [ $current_branch == "master" ]; then export DEPLOYPATH=/home/fpufutm/public_html/xyz/; fi;
    - if [ $current_branch == "develop" ]; then export DEPLOYPATH=/home/fpufutm/public_html/xyz_dev/; fi;
    - /bin/cp -R * $DEPLOYPATH
   
---
